# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(620, 570)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../ArtificialVision/feliz-1.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 251, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbtnCarpetas = QtGui.QRadioButton(self.groupBox)
        self.rbtnCarpetas.setEnabled(True)
        self.rbtnCarpetas.setGeometry(QtCore.QRect(90, 20, 82, 17))
        self.rbtnCarpetas.setChecked(True)
        self.rbtnCarpetas.setObjectName(_fromUtf8("rbtnCarpetas"))
        self.rbtnArchivos = QtGui.QRadioButton(self.groupBox)
        self.rbtnArchivos.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rbtnArchivos.setChecked(False)
        self.rbtnArchivos.setObjectName(_fromUtf8("rbtnArchivos"))
        self.btnMuestra = QtGui.QPushButton(self.groupBox)
        self.btnMuestra.setGeometry(QtCore.QRect(100, 100, 91, 23))
        self.btnMuestra.setObjectName(_fromUtf8("btnMuestra"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 141, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 160, 261, 361))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.refreshbtn = QtGui.QPushButton(self.groupBox_2)
        self.refreshbtn.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.refreshbtn.setObjectName(_fromUtf8("refreshbtn"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 241, 251))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.treeView = QtGui.QTreeView(self.tab)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 211, 211))
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.treeView_2 = QtGui.QTreeView(self.tab_2)
        self.treeView_2.setGeometry(QtCore.QRect(10, 10, 211, 201))
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 10, 281, 121))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btnTrain = QtGui.QPushButton(self.groupBox_3)
        self.btnTrain.setGeometry(QtCore.QRect(60, 70, 151, 41))
        self.btnTrain.setObjectName(_fromUtf8("btnTrain"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 20, 171, 17))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 140, 271, 381))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnAddFile = QtGui.QPushButton(self.groupBox_4)
        self.btnAddFile.setGeometry(QtCore.QRect(160, 30, 75, 23))
        self.btnAddFile.setObjectName(_fromUtf8("btnAddFile"))
        self.txtFile = QtGui.QLineEdit(self.groupBox_4)
        self.txtFile.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.txtFile.setObjectName(_fromUtf8("txtFile"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 70, 151, 161))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.imOri = QtGui.QLabel(self.tab_3)
        self.imOri.setGeometry(QtCore.QRect(10, 10, 121, 111))
        self.imOri.setAutoFillBackground(True)
        self.imOri.setText(_fromUtf8(""))
        self.imOri.setScaledContents(True)
        self.imOri.setObjectName(_fromUtf8("imOri"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.imBin = QtGui.QLabel(self.tab_4)
        self.imBin.setGeometry(QtCore.QRect(20, 20, 111, 101))
        self.imBin.setAutoFillBackground(True)
        self.imBin.setText(_fromUtf8(""))
        self.imBin.setObjectName(_fromUtf8("imBin"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.btnClasificar = QtGui.QPushButton(self.groupBox_4)
        self.btnClasificar.setGeometry(QtCore.QRect(180, 90, 61, 131))
        self.btnClasificar.setObjectName(_fromUtf8("btnClasificar"))
        self.clase = QtGui.QLabel(self.groupBox_4)
        self.clase.setGeometry(QtCore.QRect(20, 240, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clase.setFont(font)
        self.clase.setObjectName(_fromUtf8("clase"))
        self.tableView = QtGui.QTableView(self.groupBox_4)
        self.tableView.setGeometry(QtCore.QRect(20, 270, 221, 91))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNueva = QtGui.QAction(MainWindow)
        self.actionNueva.setObjectName(_fromUtf8("actionNueva"))
        self.actionAbrir = QtGui.QAction(MainWindow)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.menuArchivo.addAction(self.actionNueva)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rbtnArchivos, self.rbtnCarpetas)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Clasificacion Bayesiana", None))
        self.groupBox.setTitle(_translate("MainWindow", "Seleccion  de Muestras", None))
        self.rbtnCarpetas.setText(_translate("MainWindow", "Carpetas", None))
        self.rbtnArchivos.setText(_translate("MainWindow", "Archivos", None))
        self.btnMuestra.setText(_translate("MainWindow", "Añadir Muestra", None))
        self.label.setText(_translate("MainWindow", "Nombre del Tipo:", None))
        self.checkBox.setText(_translate("MainWindow", "Recortar", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Muestras", None))
        self.refreshbtn.setText(_translate("MainWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Originales", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Binarias", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Entrenamiento", None))
        self.btnTrain.setText(_translate("MainWindow", "Entrenar", None))
        self.radioButton_3.setText(_translate("MainWindow", "Naive Bayes Pixel", None))
        self.radioButton_4.setText(_translate("MainWindow", "Otro", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Clasificacion", None))
        self.btnAddFile.setText(_translate("MainWindow", "Añadir", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Imagen", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Binario", None))
        self.btnClasificar.setText(_translate("MainWindow", "Clasificar", None))
        self.clase.setText(_translate("MainWindow", "...", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Clasificacion", None))
        self.actionNueva.setText(_translate("MainWindow", "Nueva", None))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir", None))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar", None))

